linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - bodyclose
    - errname
    - exhaustive
    - goconst
    - gofmt
    - importas
    - nilnil
    - nlreturn
    - paralleltest
